// artifacts/mockup-sandbox/src/components/mockups/pengajuan/FormPengajuan.tsx
import { useState, useRef } from "react";

const STEPS = [
  { id: 1, label: "Data Diri" },
  { id: 2, label: "Akademis" },
  { id: 3, label: "Dokumen" },
  { id: 4, label: "Review & Kirim" },
];

const KATEGORI = [
  { value: "smk",        label: "SMK / Sekolah Menengah Kejuruan" },
  { value: "d3_s1_s2",  label: "D3 / S1 / S2 (Perguruan Tinggi)" },
  { value: "penelitian", label: "Penelitian / Riset" },
];

const DOKUMEN_LIST = [
  { key: "proposal_magang", label: "Proposal Magang",      required: true,  accept: ".pdf,.doc,.docx", hint: "PDF atau Word, maks 10 MB" },
  { key: "ktp",             label: "KTP / Kartu Identitas", required: true,  accept: "image/*,.pdf",   hint: "JPG, PNG, atau PDF" },
  { key: "ktm",             label: "KTM / Kartu Pelajar",   required: false, accept: "image/*,.pdf",   hint: "JPG, PNG, atau PDF" },
  { key: "pasfoto",         label: "Pasfoto 3×4",           required: true,  accept: "image/*",        hint: "JPG atau PNG, latar merah/biru" },
  { key: "bpjs_kis",        label: "BPJS / KIS",            required: true,  accept: "image/*,.pdf",   hint: "Foto kartu atau PDF" },
];

function Field({ label, required, children, hint }: {
  label: string; required?: boolean; children: React.ReactNode; hint?: string;
}) {
  return (
    <div className="field">
      <label className="field-label">
        {label}{required && <span style={{ color: "#e11d48" }}> *</span>}
      </label>
      {children}
      {hint && <div className="field-hint">{hint}</div>}
    </div>
  );
}

function Input(props: React.InputHTMLAttributes<HTMLInputElement>) {
  return <input className="inp" {...props} />;
}

function Select({ children, ...props }: React.SelectHTMLAttributes<HTMLSelectElement> & { children: React.ReactNode }) {
  return <select className="inp" {...props}>{children}</select>;
}

function Textarea(props: React.TextareaHTMLAttributes<HTMLTextAreaElement>) {
  return <textarea className="inp" rows={3} {...props} />;
}

/* ─── Step 1: Data Diri ─────────────── */
function StepDataDiri({ data, onChange }: { data: any; onChange: (k: string, v: string) => void }) {
  return (
    <div className="step-body">
      <div className="step-head">
        <div className="step-head__info">
          <div className="step-title">Data Diri</div>
          <div className="step-sub">Lengkapi informasi pribadi sesuai KTP</div>
        </div>
      </div>
      <div className="form-grid-2">
        <Field label="Nama Lengkap" required>
          <Input placeholder="Sesuai KTP" value={data.nama_lengkap} onChange={e => onChange("nama_lengkap", e.target.value)} />
        </Field>
        <Field label="Jenis Kelamin" required>
          <Select value={data.jenis_kelamin} onChange={e => onChange("jenis_kelamin", e.target.value)}>
            <option value="">-- Pilih --</option>
            <option value="laki_laki">Laki-laki</option>
            <option value="perempuan">Perempuan</option>
          </Select>
        </Field>
        <Field label="Tempat Lahir" required>
          <Input placeholder="Kota kelahiran" value={data.tempat_lahir} onChange={e => onChange("tempat_lahir", e.target.value)} />
        </Field>
        <Field label="Tanggal Lahir" required>
          <Input type="date" value={data.tanggal_lahir} onChange={e => onChange("tanggal_lahir", e.target.value)} />
        </Field>
        <Field label="Nomor HP / WhatsApp" required>
          <Input placeholder="08xxxxxxxxxx" value={data.no_hp} onChange={e => onChange("no_hp", e.target.value)} />
        </Field>
        <Field label="Email Aktif" required>
          <Input type="email" placeholder="nama@email.com" value={data.email} onChange={e => onChange("email", e.target.value)} />
        </Field>
      </div>
      <Field label="Alamat Lengkap" required>
        <Textarea placeholder="Jalan, nomor, kelurahan, kecamatan, kota, provinsi" value={data.alamat} onChange={e => onChange("alamat", e.target.value)} />
      </Field>
    </div>
  );
}

/* ─── Step 2: Akademis ──────────────── */
function StepAkademis({ data, onChange }: { data: any; onChange: (k: string, v: string) => void }) {
  return (
    <div className="step-body">
      <div className="step-head">
        <div className="step-head__info">
          <div className="step-title">Informasi Akademis</div>
          <div className="step-sub">Data institusi dan program studi Anda</div>
        </div>
      </div>
      <Field label="Kategori Magang" required>
        <div className="kategori-grid">
          {KATEGORI.map(k => (
            <button
              key={k.value}
              className={`kategori-btn${data.kategori_magang === k.value ? " kategori-btn--active" : ""}`}
              onClick={() => onChange("kategori_magang", k.value)}
            >
              <span className="kategori-radio" />
              <span>{k.label}</span>
            </button>
          ))}
        </div>
      </Field>
      <div className="form-grid-2">
        <Field label="Asal Institusi / Sekolah" required>
          <Input placeholder="Nama sekolah / universitas" value={data.asal_institusi} onChange={e => onChange("asal_institusi", e.target.value)} />
        </Field>
        <Field label="Jurusan / Program Studi" required>
          <Input placeholder="Teknik Informatika" value={data.jurusan} onChange={e => onChange("jurusan", e.target.value)} />
        </Field>
        <Field label={data.kategori_magang === "smk" ? "Kelas" : "Semester"} required>
          <Input placeholder={data.kategori_magang === "smk" ? "XI / XII" : "Semester 5"} value={data.kelas_semester} onChange={e => onChange("kelas_semester", e.target.value)} />
        </Field>
        <Field label={data.kategori_magang === "smk" ? "NIS / NISN" : "NIM"} required>
          <Input placeholder="Nomor induk" value={data.nomor_induk} onChange={e => onChange("nomor_induk", e.target.value)} />
        </Field>
      </div>
      <div className="info-box">
        Kategori magang menentukan dokumen yang perlu diunggah pada langkah berikutnya.
      </div>
    </div>
  );
}

/* ─── Step 3: Dokumen ───────────────── */
function FileDropZone({ dok, file, onFile }: { dok: typeof DOKUMEN_LIST[0]; file: File | null; onFile: (f: File | null) => void }) {
  const ref = useRef<HTMLInputElement>(null);
  const [drag, setDrag] = useState(false);
  const fmt = (b: number) => b > 1048576 ? `${(b / 1048576).toFixed(1)} MB` : `${(b / 1024).toFixed(0)} KB`;

  return (
    <div
      className={`dropzone${drag ? " dropzone--drag" : ""}${file ? " dropzone--done" : ""}`}
      onDragOver={e => { e.preventDefault(); setDrag(true); }}
      onDragLeave={() => setDrag(false)}
      onDrop={e => { e.preventDefault(); setDrag(false); const f = e.dataTransfer.files[0]; if (f) onFile(f); }}
      onClick={() => ref.current?.click()}
    >
      <input ref={ref} type="file" accept={dok.accept} style={{ display: "none" }} onChange={e => onFile(e.target.files?.[0] ?? null)} />
      {file ? (
        <div className="dropzone-done">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" style={{ flexShrink: 0 }}>
            <circle cx="12" cy="12" r="10" fill="#48AF4A" />
            <path d="M8 12l3 3 5-6" stroke="#fff" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
          </svg>
          <div className="dropzone-done__info">
            <div className="dropzone-done__name">{file.name}</div>
            <div className="dropzone-done__size">{fmt(file.size)}</div>
          </div>
          <button className="dropzone-done__remove" onClick={e => { e.stopPropagation(); onFile(null); }}>
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none"><path d="M18 6L6 18M6 6l12 12" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/></svg>
          </button>
        </div>
      ) : (
        <div className="dropzone-empty">
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" style={{ flexShrink: 0, color: "#9ca3af" }}>
            <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"/>
            <polyline points="17 8 12 3 7 8" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"/>
            <line x1="12" y1="3" x2="12" y2="15" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"/>
          </svg>
          <div>
            <div className="dropzone-empty__text">Klik atau drag file ke sini</div>
            <div className="dropzone-empty__hint">{dok.hint}</div>
          </div>
        </div>
      )}
    </div>
  );
}

function StepDokumen({ files, onFile }: { files: Record<string, File | null>; onFile: (k: string, f: File | null) => void }) {
  return (
    <div className="step-body">
      <div className="step-head">
        <div className="step-head__info">
          <div className="step-title">Upload Dokumen</div>
          <div className="step-sub">Unggah semua berkas yang diperlukan</div>
        </div>
      </div>
      <div className="dok-grid">
        {DOKUMEN_LIST.map(dok => (
          <div key={dok.key} className="dok-item">
            <div className="dok-item__header">
              <span className="dok-item__label">{dok.label}</span>
              {dok.required
                ? <span className="badge-required">Wajib</span>
                : <span className="badge-optional">Opsional</span>}
            </div>
            <FileDropZone dok={dok} file={files[dok.key] ?? null} onFile={f => onFile(dok.key, f)} />
          </div>
        ))}
      </div>
    </div>
  );
}

/* ─── Step 4: Review ────────────────── */
function ReviewRow({ label, value }: { label: string; value?: string }) {
  return (
    <div className="review-row">
      <div className="review-row__label">{label}</div>
      <div className="review-row__value">{value || <span style={{ color: "#d1d5db" }}>—</span>}</div>
    </div>
  );
}

function StepReview({ diri, akademis, files }: { diri: any; akademis: any; files: Record<string, File | null> }) {
  const kategoriLabel = KATEGORI.find(k => k.value === akademis.kategori_magang)?.label ?? akademis.kategori_magang;
  const uploaded = DOKUMEN_LIST.filter(d => files[d.key]).length;
  const requiredMissing = DOKUMEN_LIST.filter(d => d.required && !files[d.key]);

  return (
    <div className="step-body">
      <div className="step-head">
        <div className="step-head__info">
          <div className="step-title">Review & Kirim</div>
          <div className="step-sub">Periksa kembali data sebelum mengirim pengajuan</div>
        </div>
      </div>

      <div className="review-section">
        <div className="review-section__title">Data Diri</div>
        <div className="review-grid">
          <ReviewRow label="Nama Lengkap"  value={diri.nama_lengkap} />
          <ReviewRow label="Jenis Kelamin" value={diri.jenis_kelamin === "laki_laki" ? "Laki-laki" : diri.jenis_kelamin === "perempuan" ? "Perempuan" : ""} />
          <ReviewRow label="Tempat Lahir"  value={diri.tempat_lahir} />
          <ReviewRow label="Tanggal Lahir" value={diri.tanggal_lahir} />
          <ReviewRow label="No. HP"        value={diri.no_hp} />
          <ReviewRow label="Email"         value={diri.email} />
          <ReviewRow label="Alamat"        value={diri.alamat} />
        </div>
      </div>

      <div className="review-section">
        <div className="review-section__title">Data Akademis</div>
        <div className="review-grid">
          <ReviewRow label="Kategori"      value={kategoriLabel} />
          <ReviewRow label="Institusi"     value={akademis.asal_institusi} />
          <ReviewRow label="Jurusan"       value={akademis.jurusan} />
          <ReviewRow label="Kelas/Semester" value={akademis.kelas_semester} />
          <ReviewRow label="Nomor Induk"   value={akademis.nomor_induk} />
        </div>
      </div>

      <div className="review-section">
        <div className="review-section__title">Dokumen</div>
        <div className="dok-status-grid">
          {DOKUMEN_LIST.map(d => (
            <div key={d.key} className={`dok-status${files[d.key] ? " dok-status--ok" : d.required ? " dok-status--miss" : ""}`}>
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none">
                {files[d.key]
                  ? <><circle cx="12" cy="12" r="10" fill="#16a34a"/><path d="M8 12l3 3 5-6" stroke="#fff" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/></>
                  : d.required
                    ? <><circle cx="12" cy="12" r="10" fill="#fecaca"/><path d="M15 9l-6 6M9 9l6 6" stroke="#dc2626" strokeWidth="2" strokeLinecap="round"/></>
                    : <circle cx="12" cy="12" r="10" stroke="#d1d5db" strokeWidth="1.5" fill="none"/>
                }
              </svg>
              <span>{d.label}</span>
              {d.required && !files[d.key] && <span className="dok-missing">Belum upload</span>}
            </div>
          ))}
        </div>
      </div>

      {requiredMissing.length > 0 && (
        <div className="alert-warn">
          Masih ada {requiredMissing.length} dokumen wajib yang belum diunggah. Kembali ke langkah Dokumen untuk melengkapinya.
        </div>
      )}

      <div className="review-note">
        Pastikan semua data sudah benar. Pengajuan yang sudah dikirim tidak dapat diedit. Tim HRD akan memverifikasi berkas dalam <strong>3–5 hari kerja</strong>.
      </div>

      <div style={{ position: "relative", marginTop: 4 }}>
        <div className="upload-bar">
          <div className="upload-bar__fill" style={{ width: `${Math.round(uploaded / DOKUMEN_LIST.length * 100)}%` }} />
        </div>
        <div className="upload-bar__label">{uploaded}/{DOKUMEN_LIST.length} dokumen diunggah</div>
      </div>
    </div>
  );
}

/* ─── MAIN ──────────────────────────── */
export default function FormPengajuan() {
  const [step, setStep] = useState(1);
  const [submitted, setSubmitted] = useState(false);

  const [diri, setDiri] = useState({
    nama_lengkap: "Budi Santoso", tempat_lahir: "Palembang",
    tanggal_lahir: "2003-05-12", jenis_kelamin: "laki_laki",
    no_hp: "081234567890", email: "budi@student.ac.id",
    alamat: "Jl. Mawar No.12, Kel. Ilir, Kec. Ilir Barat, Palembang, Sumatera Selatan",
  });
  const [akademis, setAkademis] = useState({
    kategori_magang: "d3_s1_s2", asal_institusi: "Universitas Sriwijaya",
    jurusan: "Teknik Informatika", kelas_semester: "Semester 5",
    nomor_induk: "09021282025082",
  });
  const [files, setFiles] = useState<Record<string, File | null>>({
    proposal_magang: null, ktp: null, ktm: null, pasfoto: null, bpjs_kis: null,
  });

  if (submitted) {
    return (
      <div style={{ minHeight: "100vh", display: "flex", alignItems: "center", justifyContent: "center", background: "#f0fdf4", fontFamily: "Poppins, sans-serif" }}>
        <div style={{ textAlign: "center", padding: "48px 40px", background: "#fff", borderRadius: 20, boxShadow: "0 8px 40px rgba(13,40,24,0.10)", maxWidth: 460 }}>
          <div style={{ width: 64, height: 64, borderRadius: "50%", background: "#f0fdf4", display: "flex", alignItems: "center", justifyContent: "center", margin: "0 auto 20px" }}>
            <svg width="32" height="32" viewBox="0 0 24 24" fill="none">
              <circle cx="12" cy="12" r="10" fill="#48AF4A"/>
              <path d="M8 12l3 3 5-6" stroke="#fff" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"/>
            </svg>
          </div>
          <div style={{ fontSize: 20, fontWeight: 800, color: "#0d2818", marginBottom: 8 }}>Pengajuan Berhasil Dikirim</div>
          <div style={{ fontSize: 13, color: "#6b7280", marginBottom: 24, lineHeight: 1.7 }}>
            Pengajuan magang Anda telah diterima sistem.<br />
            Tim HRD akan memverifikasi berkas dalam <strong>3–5 hari kerja</strong>.
          </div>
          <div style={{ background: "#f0fdf4", borderRadius: 10, padding: "12px 20px", fontSize: 13, color: "#16a34a", fontWeight: 600, marginBottom: 20 }}>
            Status: Menunggu Verifikasi
          </div>
          <button style={{ background: "#48AF4A", color: "#fff", border: "none", borderRadius: 10, padding: "11px 28px", fontSize: 13, fontWeight: 700, cursor: "pointer", fontFamily: "Poppins, sans-serif" }} onClick={() => setSubmitted(false)}>
            Lihat Status Pengajuan
          </button>
        </div>
      </div>
    );
  }

  return (
    <>
      <style>{`
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { background: #f0fdf4; font-family: 'Poppins', sans-serif; }

        .shell {
          min-height: 100vh;
          display: flex;
          align-items: flex-start;
          justify-content: center;
          padding: 28px 16px 48px;
          background: linear-gradient(160deg, #f0fdf4 0%, #e8f5e9 100%);
        }
        .card {
          width: 100%;
          max-width: 760px;
          background: #fff;
          border-radius: 18px;
          box-shadow: 0 4px 32px rgba(13,40,24,0.09), 0 1px 4px rgba(13,40,24,0.05);
          overflow: hidden;
        }

        /* Header */
        .card-header {
          background: linear-gradient(135deg, #0d2818 0%, #1a5c20 100%);
          padding: 20px 28px 18px;
        }
        .card-header__title { font-size: 15px; font-weight: 800; color: #fff; }
        .card-header__sub   { font-size: 11.5px; color: rgba(255,255,255,0.50); margin-top: 3px; }

        /* Stepper */
        .stepper {
          display: flex;
          align-items: flex-start;
          padding: 20px 28px 16px;
          border-bottom: 1px solid #f0faf0;
          gap: 0;
        }
        .stepper-item { flex: 1; display: flex; align-items: flex-start; }
        .stepper-item:last-child .stepper-line { display: none; }
        .stepper-col { display: flex; flex-direction: column; align-items: center; gap: 7px; }
        .stepper-dot {
          width: 30px; height: 30px; border-radius: 50%;
          background: #f3f4f6; color: #9ca3af;
          font-size: 12px; font-weight: 700;
          display: flex; align-items: center; justify-content: center;
          flex-shrink: 0; transition: all 0.2s;
          border: 2px solid transparent;
        }
        .stepper-dot--active { background: #48AF4A; color: #fff; border-color: #48AF4A; box-shadow: 0 0 0 4px rgba(72,175,74,0.15); }
        .stepper-dot--done   { background: #0d2818; color: #86efac; border-color: #0d2818; }
        .stepper-label { font-size: 10px; font-weight: 600; color: #d1d5db; white-space: nowrap; }
        .stepper-label--active { color: #48AF4A; }
        .stepper-label--done   { color: #374151; }
        .stepper-line {
          flex: 1; height: 2px; background: #e5e7eb;
          margin: 14px 6px 0; transition: background 0.2s;
        }
        .stepper-line--done { background: #48AF4A; }

        /* Body */
        .step-body { padding: 22px 28px; display: flex; flex-direction: column; gap: 16px; }
        .step-head { display: flex; align-items: center; gap: 12px; margin-bottom: 2px; }
        .step-head__info {}
        .step-title { font-size: 14px; font-weight: 800; color: #0d2818; }
        .step-sub   { font-size: 11.5px; color: #9ca3af; margin-top: 2px; }

        /* Fields */
        .form-grid-2 { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }
        .field { display: flex; flex-direction: column; gap: 5px; }
        .field-label { font-size: 11.5px; font-weight: 600; color: #374151; }
        .field-hint  { font-size: 10.5px; color: #9ca3af; }
        .inp {
          border: 1.5px solid #e5e7eb; border-radius: 9px;
          padding: 9px 12px; font-size: 13px; font-family: 'Poppins', sans-serif;
          color: #111827; outline: none; width: 100%; background: #fff;
          transition: border-color 0.15s; appearance: none;
        }
        .inp:focus { border-color: #48AF4A; box-shadow: 0 0 0 3px rgba(72,175,74,0.10); }
        textarea.inp { resize: vertical; }

        /* Kategori picker */
        .kategori-grid { display: flex; flex-direction: column; gap: 7px; }
        .kategori-btn {
          display: flex; align-items: center; gap: 11px;
          padding: 11px 14px; border-radius: 9px;
          border: 1.5px solid #e5e7eb; background: #fff;
          font-size: 13px; font-family: 'Poppins', sans-serif;
          color: #374151; cursor: pointer; text-align: left;
          transition: all 0.15s;
        }
        .kategori-btn--active { border-color: #48AF4A; background: #f0fdf4; color: #0d2818; font-weight: 600; }
        .kategori-radio {
          width: 14px; height: 14px; border-radius: 50%;
          border: 2px solid #d1d5db; flex-shrink: 0;
          transition: all 0.15s;
        }
        .kategori-btn--active .kategori-radio {
          border-color: #48AF4A; background: #48AF4A;
          box-shadow: inset 0 0 0 3px #fff;
        }

        /* Info box */
        .info-box {
          background: #eff6ff; border: 1px solid #bfdbfe; border-radius: 9px;
          padding: 11px 14px; font-size: 12px; color: #1d4ed8; line-height: 1.6;
        }

        /* Dokumen */
        .dok-grid { display: flex; flex-direction: column; gap: 12px; }
        .dok-item { display: flex; flex-direction: column; gap: 5px; }
        .dok-item__header { display: flex; align-items: center; gap: 7px; }
        .dok-item__label { font-size: 12px; font-weight: 600; color: #374151; }
        .badge-required { background: #fef2f2; color: #dc2626; border-radius: 100px; padding: 2px 8px; font-size: 10px; font-weight: 700; }
        .badge-optional { background: #f3f4f6; color: #6b7280;  border-radius: 100px; padding: 2px 8px; font-size: 10px; font-weight: 600; }

        .dropzone {
          border: 2px dashed #d1d5db; border-radius: 9px;
          padding: 12px 14px; cursor: pointer; transition: all 0.15s; background: #fafafa;
        }
        .dropzone:hover, .dropzone--drag { border-color: #48AF4A; background: #f0fdf4; }
        .dropzone--done { border-style: solid; border-color: #48AF4A; background: #f0fdf4; }
        .dropzone-empty { display: flex; align-items: center; gap: 10px; }
        .dropzone-empty__text { font-size: 12.5px; color: #374151; font-weight: 500; }
        .dropzone-empty__hint { font-size: 11px; color: #9ca3af; margin-top: 1px; }
        .dropzone-done { display: flex; align-items: center; gap: 10px; }
        .dropzone-done__info { flex: 1; }
        .dropzone-done__name { font-size: 12.5px; font-weight: 600; color: #0d2818; }
        .dropzone-done__size { font-size: 11px; color: #6b7280; }
        .dropzone-done__remove {
          background: none; border: none; color: #9ca3af;
          cursor: pointer; padding: 4px; border-radius: 4px;
          display: flex; align-items: center;
        }
        .dropzone-done__remove:hover { background: #fee2e2; color: #dc2626; }

        /* Review */
        .review-section { background: #fafafa; border-radius: 11px; padding: 14px 16px; display: flex; flex-direction: column; gap: 10px; }
        .review-section__title { font-size: 11.5px; font-weight: 700; color: #0d2818; text-transform: uppercase; letter-spacing: 0.05em; padding-bottom: 8px; border-bottom: 1px solid #e5e7eb; }
        .review-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 8px; }
        .review-row { display: flex; flex-direction: column; gap: 2px; }
        .review-row__label { font-size: 10.5px; color: #9ca3af; }
        .review-row__value { font-size: 12.5px; font-weight: 600; color: #111827; }
        .dok-status-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 6px; }
        .dok-status { display: flex; align-items: center; gap: 7px; font-size: 12px; color: #6b7280; }
        .dok-status--ok   { color: #16a34a; font-weight: 600; }
        .dok-status--miss { color: #dc2626; }
        .dok-missing { font-size: 10px; color: #dc2626; font-weight: 600; margin-left: auto; }

        .review-note {
          background: #fffbeb; border: 1px solid #fde68a;
          border-radius: 9px; padding: 11px 14px; font-size: 12px; color: #78350f; line-height: 1.6;
        }
        .alert-warn {
          background: #fef2f2; border: 1px solid #fecaca;
          border-radius: 9px; padding: 11px 14px; font-size: 12px; color: #dc2626;
        }
        .upload-bar { background: #e5e7eb; border-radius: 100px; height: 6px; overflow: hidden; }
        .upload-bar__fill { height: 100%; background: #48AF4A; border-radius: 100px; transition: width 0.3s; }
        .upload-bar__label { font-size: 10.5px; color: #6b7280; margin-top: 5px; text-align: right; }

        /* Footer */
        .card-footer {
          padding: 14px 28px;
          border-top: 1px solid #f0faf0;
          display: flex; align-items: center; justify-content: space-between;
          background: #fafafa;
        }
        .step-counter { font-size: 11px; color: #9ca3af; }
        .btn-back {
          background: #fff; border: 1.5px solid #e5e7eb; color: #374151;
          border-radius: 9px; padding: 9px 20px; font-size: 13px; font-weight: 600;
          font-family: 'Poppins', sans-serif; cursor: pointer; transition: all 0.15s;
        }
        .btn-back:hover { border-color: #48AF4A; color: #0d2818; }
        .btn-next {
          background: #48AF4A; color: #fff; border: none;
          border-radius: 9px; padding: 9px 24px;
          font-size: 13px; font-weight: 700;
          font-family: 'Poppins', sans-serif; cursor: pointer;
          transition: background 0.15s;
        }
        .btn-next:hover { background: #3d9e3f; }
        .btn-submit { background: #0d2818; }
        .btn-submit:hover { background: #1a5c20; }
      `}</style>

      <div className="shell">
        <div className="card">
          <div className="card-header">
            <div className="card-header__title">Formulir Pengajuan Magang</div>
            <div className="card-header__sub">PT TanjungEnim Lestari Pulp and Paper (TELPP)</div>
          </div>

          <div className="stepper">
            {STEPS.map((s, i) => {
              const done   = step > s.id;
              const active = step === s.id;
              return (
                <div key={s.id} className="stepper-item">
                  <div className="stepper-col">
                    <div className={`stepper-dot${active ? " stepper-dot--active" : done ? " stepper-dot--done" : ""}`}>
                      {done
                        ? <svg width="12" height="12" viewBox="0 0 24 24" fill="none"><path d="M5 13l4 4L19 7" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"/></svg>
                        : s.id
                      }
                    </div>
                    <div className={`stepper-label${active ? " stepper-label--active" : done ? " stepper-label--done" : ""}`}>
                      {s.label}
                    </div>
                  </div>
                  {i < STEPS.length - 1 && (
                    <div className={`stepper-line${done ? " stepper-line--done" : ""}`} />
                  )}
                </div>
              );
            })}
          </div>

          {step === 1 && <StepDataDiri  data={diri}    onChange={(k,v) => setDiri(p => ({...p,[k]:v}))} />}
          {step === 2 && <StepAkademis data={akademis} onChange={(k,v) => setAkademis(p => ({...p,[k]:v}))} />}
          {step === 3 && <StepDokumen  files={files}   onFile={(k,f) => setFiles(p => ({...p,[k]:f}))} />}
          {step === 4 && <StepReview   diri={diri}     akademis={akademis} files={files} />}

          <div className="card-footer">
            <div>
              {step > 1 && <button className="btn-back" onClick={() => setStep(s => s - 1)}>Kembali</button>}
            </div>
            <div className="step-counter">Langkah {step} dari {STEPS.length}</div>
            <button
              className={`btn-next${step === 4 ? " btn-submit" : ""}`}
              onClick={() => step < 4 ? setStep(s => s + 1) : setSubmitted(true)}
            >
              {step === 4 ? "Kirim Pengajuan" : "Lanjut"}
            </button>
          </div>
        </div>
      </div>
    </>
  );
}

// artifacts/frontend/src/views/FormPengajuan.vue
<template>
  <div class="form-page">
    <!-- Navbar minimal -->
    <nav class="form-nav">
      <div class="form-nav__inner">
        <router-link to="/" class="form-nav__brand">
          <img src="/logotel.png" alt="PT TELPP" class="form-nav__logo" />
          <span>e-Magang <strong>PT TELPP</strong></span>
        </router-link>
        <router-link to="/login" class="form-nav__login">Sudah punya akun? Masuk →</router-link>
      </div>
    </nav>

    <!-- Success screen -->
    <div v-if="submitted" class="success-wrap">
      <div class="success-card">
        <div class="success-icon">
          <svg width="48" height="48" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="11" fill="#dcfce7"/><path d="M7 12l3.5 3.5L17 8" stroke="#16a34a" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/></svg>
        </div>
        <h2>Pengajuan Berhasil Dikirim!</h2>
        <p>
          Terima kasih, <strong>{{ diri.nama_lengkap }}</strong>. Tim HRD PT TELPP akan meninjau
          pengajuan Anda dan mengirimkan akun login ke
          <strong>{{ diri.email }}</strong> setelah verifikasi selesai.
        </p>
        <div class="success-info">
          <div class="success-info__item">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M12 22c5.523 0 10-4.477 10-10S17.523 2 12 2 2 6.477 2 12s4.477 10 10 10z" stroke="#48AF4A" stroke-width="2"/><path d="M12 6v6l4 2" stroke="#48AF4A" stroke-width="2" stroke-linecap="round"/></svg>
            Proses verifikasi 3–5 hari kerja
          </div>
          <div class="success-info__item">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z" stroke="#48AF4A" stroke-width="2"/><polyline points="22,6 12,13 2,6" stroke="#48AF4A" stroke-width="2"/></svg>
            Notifikasi dikirim via email
          </div>
        </div>
        <router-link to="/" class="btn-primary">Kembali ke Halaman Utama</router-link>
      </div>
    </div>

    <!-- Form -->
    <div v-else class="form-wrap">
      <div class="form-card">
        <!-- Header -->
        <div class="form-header">
          <h1>Formulir Pengajuan Magang</h1>
          <p>PT TanjungEnim Lestari Pulp and Paper · Muara Enim, Sumatera Selatan</p>
        </div>

        <!-- Stepper -->
        <div class="stepper">
          <div
            v-for="(s, i) in STEPS"
            :key="i"
            class="stepper__item"
            :class="{
              'stepper__item--active': step === i,
              'stepper__item--done': step > i,
            }"
          >
            <div class="stepper__circle">
              <svg v-if="step > i" width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M5 13l4 4L19 7" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/></svg>
              <span v-else>{{ i + 1 }}</span>
            </div>
            <div class="stepper__label">{{ s }}</div>
            <div v-if="i < STEPS.length - 1" class="stepper__line"></div>
          </div>
        </div>

        <!-- STEP 1: Data Diri -->
        <div v-if="step === 0" class="form-section">
          <h3 class="section-title">Data Diri</h3>
          <div class="form-grid">
            <div class="field field--full">
              <label>Nama Lengkap <span class="req">*</span></label>
              <input v-model="diri.nama_lengkap" type="text" placeholder="Sesuai KTP/KTM" />
            </div>
            <div class="field">
              <label>Tempat Lahir <span class="req">*</span></label>
              <input v-model="diri.tempat_lahir" type="text" placeholder="Kota kelahiran" />
            </div>
            <div class="field">
              <label>Tanggal Lahir <span class="req">*</span></label>
              <input v-model="diri.tanggal_lahir" type="date" />
            </div>
            <div class="field">
              <label>Jenis Kelamin <span class="req">*</span></label>
              <select v-model="diri.jenis_kelamin">
                <option value="">-- Pilih --</option>
                <option value="laki_laki">Laki-laki</option>
                <option value="perempuan">Perempuan</option>
              </select>
            </div>
            <div class="field">
              <label>No. HP / WhatsApp <span class="req">*</span></label>
              <input v-model="diri.no_hp" type="tel" placeholder="08xxxxxxxxxx" />
            </div>
            <div class="field">
              <label>Email Aktif <span class="req">*</span></label>
              <input v-model="diri.email" type="email" placeholder="email@contoh.com" />
              <div class="field-hint">Akun login akan dikirim ke email ini</div>
            </div>
            <div class="field field--full">
              <label>Alamat Lengkap <span class="req">*</span></label>
              <textarea v-model="diri.alamat" rows="3" placeholder="Jalan, RT/RW, Kelurahan, Kecamatan, Kab/Kota"></textarea>
            </div>
          </div>
        </div>

        <!-- STEP 2: Data Akademis -->
        <div v-else-if="step === 1" class="form-section">
          <h3 class="section-title">Data Akademis</h3>
          <div class="form-grid">
            <div class="field field--full">
              <label>Kategori Magang <span class="req">*</span></label>
              <div class="radio-group">
                <label
                  v-for="k in KATEGORI"
                  :key="k.value"
                  class="radio-card"
                  :class="{ 'radio-card--active': akademis.kategori_magang === k.value }"
                >
                  <input type="radio" :value="k.value" v-model="akademis.kategori_magang" />
                  <div class="radio-card__label">{{ k.label }}</div>
                  <div class="radio-card__sub">{{ k.sub }}</div>
                </label>
              </div>
            </div>
            <div class="field field--full">
              <label>Nama Institusi <span class="req">*</span></label>
              <input v-model="akademis.asal_institusi" type="text" placeholder="Nama universitas / sekolah" />
            </div>
            <div class="field">
              <label>Jurusan / Program Studi <span class="req">*</span></label>
              <input v-model="akademis.jurusan" type="text" placeholder="Teknik Informatika, Akuntansi, dll" />
            </div>
            <div class="field">
              <label>Semester / Kelas <span class="req">*</span></label>
              <input v-model="akademis.kelas_semester" type="text" placeholder="Semester 6 / Kelas XII TKJ" />
            </div>
            <div class="field field--full">
              <label>NIM / NIS <span class="req">*</span></label>
              <input v-model="akademis.nomor_induk" type="text" placeholder="Nomor induk mahasiswa / siswa" />
            </div>
          </div>
        </div>

        <!-- STEP 3: Review & Kirim -->
        <div v-else-if="step === 2" class="form-section">
          <h3 class="section-title">Periksa & Kirim</h3>
          <p class="review-sub">Pastikan semua data di bawah sudah benar sebelum mengirim.</p>

          <div class="review-block">
            <div class="review-block__title">Data Diri</div>
            <div class="review-grid">
              <div class="review-item"><span>Nama</span><strong>{{ diri.nama_lengkap }}</strong></div>
              <div class="review-item"><span>Tempat, Tgl Lahir</span><strong>{{ diri.tempat_lahir }}, {{ formatDate(diri.tanggal_lahir) }}</strong></div>
              <div class="review-item"><span>Jenis Kelamin</span><strong>{{ diri.jenis_kelamin === 'laki_laki' ? 'Laki-laki' : 'Perempuan' }}</strong></div>
              <div class="review-item"><span>No. HP</span><strong>{{ diri.no_hp }}</strong></div>
              <div class="review-item"><span>Email</span><strong>{{ diri.email }}</strong></div>
              <div class="review-item review-item--full"><span>Alamat</span><strong>{{ diri.alamat }}</strong></div>
            </div>
          </div>

          <div class="review-block">
            <div class="review-block__title">Data Akademis</div>
            <div class="review-grid">
              <div class="review-item"><span>Kategori</span><strong>{{ labelKategori(akademis.kategori_magang) }}</strong></div>
              <div class="review-item"><span>Institusi</span><strong>{{ akademis.asal_institusi }}</strong></div>
              <div class="review-item"><span>Jurusan</span><strong>{{ akademis.jurusan }}</strong></div>
              <div class="review-item"><span>Semester/Kelas</span><strong>{{ akademis.kelas_semester }}</strong></div>
              <div class="review-item"><span>NIM/NIS</span><strong>{{ akademis.nomor_induk }}</strong></div>
            </div>
          </div>

          <div class="review-notice">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" stroke="#0ea5e9" stroke-width="2" stroke-linecap="round"/></svg>
            Setelah pengajuan dikirim, tim HRD akan mengirimkan akun login ke <strong>{{ diri.email }}</strong>.
          </div>

          <div v-if="submitError" class="error-banner">{{ submitError }}</div>
        </div>

        <!-- Footer actions -->
        <div class="form-footer">
          <button v-if="step > 0" class="btn-outline" @click="step--">← Kembali</button>
          <div v-else></div>

          <button
            v-if="step < 2"
            class="btn-primary"
            @click="nextStep"
          >
            Lanjut →
          </button>
          <button
            v-else
            class="btn-primary"
            :disabled="submitting"
            @click="submitForm"
          >
            <span v-if="submitting" class="spinner-sm"></span>
            {{ submitting ? "Mengirim..." : "Kirim Pengajuan" }}
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive } from "vue";
import api from "@/lib/api";

const STEPS = ["Data Diri", "Akademis", "Review & Kirim"];

const KATEGORI = [
  { value: "smk",           label: "Siswa SMK (Prakerin)",    sub: "Praktik kerja industri bagi siswa SMK" },
  { value: "d3_s1_s2",      label: "Mahasiswa D3/S1/S2",      sub: "Program magang untuk mahasiswa aktif" },
  { value: "penelitian",    label: "Penelitian / Riset",      sub: "Penelitian skripsi, tesis, atau disertasi" },
];

const step = ref(0);
const submitted = ref(false);
const submitting = ref(false);
const submitError = ref<string | null>(null);

const diri = reactive({
  nama_lengkap: "",
  tempat_lahir: "",
  tanggal_lahir: "",
  jenis_kelamin: "",
  no_hp: "",
  email: "",
  alamat: "",
});

const akademis = reactive({
  kategori_magang: "",
  asal_institusi: "",
  jurusan: "",
  kelas_semester: "",
  nomor_induk: "",
});

function formatDate(d: string) {
  if (!d) return "-";
  const dt = new Date(d);
  return dt.toLocaleDateString("id-ID", { day: "2-digit", month: "long", year: "numeric" });
}

function labelKategori(k: string) {
  return KATEGORI.find(c => c.value === k)?.label ?? k;
}

function validateStep0(): string | null {
  if (!diri.nama_lengkap.trim()) return "Nama lengkap wajib diisi";
  if (!diri.tempat_lahir.trim()) return "Tempat lahir wajib diisi";
  if (!diri.tanggal_lahir) return "Tanggal lahir wajib diisi";
  if (!diri.jenis_kelamin) return "Jenis kelamin wajib dipilih";
  if (!diri.no_hp.trim()) return "Nomor HP wajib diisi";
  if (!diri.email.trim() || !diri.email.includes("@")) return "Email aktif wajib diisi";
  if (!diri.alamat.trim()) return "Alamat lengkap wajib diisi";
  return null;
}

function validateStep1(): string | null {
  if (!akademis.kategori_magang) return "Kategori magang wajib dipilih";
  if (!akademis.asal_institusi.trim()) return "Nama institusi wajib diisi";
  if (!akademis.jurusan.trim()) return "Jurusan wajib diisi";
  if (!akademis.kelas_semester.trim()) return "Semester/kelas wajib diisi";
  if (!akademis.nomor_induk.trim()) return "NIM/NIS wajib diisi";
  return null;
}

function nextStep() {
  submitError.value = null;
  const err = step.value === 0 ? validateStep0() : validateStep1();
  if (err) {
    submitError.value = err;
    return;
  }
  submitError.value = null;
  step.value++;
}

async function submitForm() {
  submitting.value = true;
  submitError.value = null;
  try {
    await api.post("/api/pengajuan/publik", {
      step1: {
        nama_lengkap: diri.nama_lengkap,
        tempat_lahir: diri.tempat_lahir,
        tanggal_lahir: diri.tanggal_lahir,
        jenis_kelamin: diri.jenis_kelamin,
        no_hp: diri.no_hp,
        email: diri.email,
        alamat: diri.alamat,
      },
      step2: {
        kategori_magang: akademis.kategori_magang,
        asal_institusi: akademis.asal_institusi,
        jurusan: akademis.jurusan,
        kelas_semester: akademis.kelas_semester,
        nomor_induk: akademis.nomor_induk,
      },
    });
    submitted.value = true;
  } catch (e: any) {
    submitError.value = e.response?.data?.message ?? "Terjadi kesalahan saat mengirim formulir. Silakan coba lagi.";
  } finally {
    submitting.value = false;
  }
}
</script>

<style scoped>
/* ── layout ── */
.form-page { min-height: 100vh; background: #f0fdf4; font-family: "Poppins", "Segoe UI", sans-serif; }

/* ── navbar ── */
.form-nav { background: #fff; border-bottom: 1px solid #e5e7eb; position: sticky; top: 0; z-index: 20; }
.form-nav__inner { max-width: 760px; margin: 0 auto; padding: 0 24px; height: 60px; display: flex; align-items: center; justify-content: space-between; }
.form-nav__brand { display: flex; align-items: center; gap: 8px; text-decoration: none; font-size: 15px; font-weight: 700; color: #0b1c30; }
.form-nav__brand strong { color: #48AF4A; }
.form-nav__logo { height: 28px; width: auto; }
.form-nav__login { font-size: 13px; font-weight: 600; color: #48AF4A; text-decoration: none; }
.form-nav__login:hover { text-decoration: underline; }

/* ── success ── */
.success-wrap { display: flex; align-items: center; justify-content: center; min-height: calc(100vh - 60px); padding: 40px 24px; }
.success-card { background: #fff; border-radius: 20px; padding: 48px 40px; max-width: 480px; width: 100%; text-align: center; box-shadow: 0 4px 32px rgba(0,0,0,0.08); }
.success-icon { margin-bottom: 20px; }
.success-card h2 { font-size: 22px; font-weight: 800; color: #0d2818; margin: 0 0 12px; }
.success-card p { font-size: 14px; color: #64748b; line-height: 1.7; margin: 0 0 24px; }
.success-info { display: flex; flex-direction: column; gap: 10px; margin-bottom: 28px; }
.success-info__item { display: flex; align-items: center; gap: 8px; font-size: 13px; color: #374151; background: #f0fdf4; border-radius: 8px; padding: 10px 14px; }

/* ── form wrap ── */
.form-wrap { display: flex; align-items: flex-start; justify-content: center; min-height: calc(100vh - 60px); padding: 40px 24px; }
.form-card { background: #fff; border-radius: 20px; padding: 40px; max-width: 720px; width: 100%; box-shadow: 0 4px 32px rgba(0,0,0,0.06); border: 1px solid #e9f5e9; }

/* ── header ── */
.form-header { text-align: center; margin-bottom: 32px; }
.form-header h1 { font-size: 22px; font-weight: 800; color: #0d2818; margin: 0 0 6px; }
.form-header p { font-size: 13px; color: #6b7280; margin: 0; }

/* ── stepper ── */
.stepper { display: flex; align-items: flex-start; justify-content: center; gap: 0; margin-bottom: 36px; }
.stepper__item { display: flex; align-items: center; position: relative; }
.stepper__circle {
  width: 32px; height: 32px; border-radius: 50%; border: 2px solid #d1d5db;
  display: flex; align-items: center; justify-content: center;
  font-size: 13px; font-weight: 700; color: #9ca3af; background: #fff; flex-shrink: 0;
  transition: all 0.2s;
}
.stepper__item--active .stepper__circle { border-color: #48AF4A; color: #48AF4A; }
.stepper__item--done .stepper__circle { border-color: #48AF4A; background: #48AF4A; color: #fff; }
.stepper__label { font-size: 12px; font-weight: 600; color: #9ca3af; margin: 0 8px; white-space: nowrap; }
.stepper__item--active .stepper__label { color: #48AF4A; }
.stepper__item--done .stepper__label { color: #0d2818; }
.stepper__line { width: 48px; height: 2px; background: #e5e7eb; margin: 0; flex-shrink: 0; }
.stepper__item--done .stepper__line { background: #48AF4A; }

/* ── section title ── */
.section-title { font-size: 15px; font-weight: 700; color: #0d2818; margin: 0 0 20px; }

/* ── form grid ── */
.form-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }
.field { display: flex; flex-direction: column; gap: 6px; }
.field--full { grid-column: 1 / -1; }
.field label { font-size: 12.5px; font-weight: 600; color: #374151; }
.req { color: #ef4444; }
.field input,
.field select,
.field textarea {
  border: 1.5px solid #e5e7eb; border-radius: 8px; padding: 10px 12px;
  font-size: 13px; font-family: inherit; color: #111827; outline: none;
  transition: border-color 0.15s; background: #fff;
}
.field input:focus, .field select:focus, .field textarea:focus { border-color: #48AF4A; }
.field textarea { resize: vertical; }
.field-hint { font-size: 11px; color: #9ca3af; }

/* ── radio kategori ── */
.radio-group { display: grid; grid-template-columns: repeat(3, 1fr); gap: 10px; }
.radio-card {
  border: 1.5px solid #e5e7eb; border-radius: 10px; padding: 14px 12px;
  cursor: pointer; transition: all 0.15s; display: flex; flex-direction: column; gap: 4px;
}
.radio-card input { display: none; }
.radio-card--active { border-color: #48AF4A; background: #f0fdf4; }
.radio-card__label { font-size: 12.5px; font-weight: 700; color: #111827; }
.radio-card__sub { font-size: 11px; color: #6b7280; line-height: 1.5; }
.radio-card--active .radio-card__label { color: #0d2818; }

/* ── review ── */
.review-sub { font-size: 13px; color: #6b7280; margin: 0 0 20px; }
.review-block { border: 1px solid #e9f5e9; border-radius: 12px; overflow: hidden; margin-bottom: 16px; }
.review-block__title { background: #f0fdf4; padding: 10px 16px; font-size: 12px; font-weight: 700; color: #0d2818; text-transform: uppercase; letter-spacing: 0.06em; }
.review-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 0; padding: 12px 16px; }
.review-item { padding: 6px 0; }
.review-item--full { grid-column: 1 / -1; }
.review-item span { display: block; font-size: 11px; color: #9ca3af; font-weight: 500; }
.review-item strong { display: block; font-size: 13px; color: #111827; font-weight: 600; margin-top: 2px; }
.review-notice { display: flex; align-items: flex-start; gap: 8px; background: #f0f9ff; border: 1px solid #bae6fd; border-radius: 10px; padding: 12px 14px; font-size: 12.5px; color: #0369a1; margin-top: 16px; }

/* ── errors ── */
.error-banner { background: #fef2f2; border: 1px solid #fca5a5; border-radius: 8px; padding: 12px 14px; font-size: 13px; color: #dc2626; margin-top: 16px; }

/* ── footer ── */
.form-footer { display: flex; align-items: center; justify-content: space-between; margin-top: 28px; padding-top: 20px; border-top: 1px solid #f3f4f6; }
.btn-primary {
  background: #48AF4A; color: #fff; border: none; border-radius: 100px;
  padding: 11px 28px; font-size: 14px; font-weight: 700; cursor: pointer;
  font-family: inherit; display: inline-flex; align-items: center; gap: 6px;
  text-decoration: none; transition: opacity 0.15s;
}
.btn-primary:hover { opacity: 0.9; }
.btn-primary:disabled { opacity: 0.6; cursor: not-allowed; }
.btn-outline {
  background: none; border: 1.5px solid #d1d5db; border-radius: 100px;
  padding: 10px 24px; font-size: 13.5px; font-weight: 600; color: #374151;
  cursor: pointer; font-family: inherit; transition: border-color 0.15s;
}
.btn-outline:hover { border-color: #48AF4A; color: #48AF4A; }

/* ── spinner ── */
.spinner-sm { width: 14px; height: 14px; border: 2px solid rgba(255,255,255,0.4); border-top-color: #fff; border-radius: 50%; animation: spin 0.6s linear infinite; }
@keyframes spin { to { transform: rotate(360deg); } }

/* ── responsive ── */
@media (max-width: 600px) {
  .form-card { padding: 24px 16px; }
  .form-grid { grid-template-columns: 1fr; }
  .radio-group { grid-template-columns: 1fr; }
  .review-grid { grid-template-columns: 1fr; }
  .stepper__line { width: 24px; }
}
</style>
